# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5e70df1a7bb5f026902180d0abd729a51465e76b2c5d989b50a1985dac2d982067c857e9ddc5db2368d97099849150c399752cca674ef497c844eaf0d542120

test:
  secret_key_base: 00d5e919b8aca35fc04a93c78114fd2197d818305ec41b81315fae82f04e3688a40791d2a0f347eb6ece52a7bb81952d944eae0fdd0d4c13abdeea0ad96ced39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
